In [49]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0 
# (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
import numpy as np
N = 10
list_ = list(reversed(range(N)))
list_numpy_ = np.array(list_)
print(list_numpy_)

[9 8 7 6 5 4 3 2 1 0]


In [68]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.
M = 5
M_matrix = np.diag(np.arange(0,M,1)[::-1], k=0) # создаем матрицу M-размерности
print(M_matrix)
sum_diag = sum(np.diag(M_matrix)) # Находим сумму элементов диагонали матрицы М
print(sum_diag)

[[4 0 0 0 0]
 [0 3 0 0 0]
 [0 0 2 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
10


In [70]:
# Задание 3
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

a = np.array( [ [4,2,1], [1,3,0], [0,5,4] ] )
b = np.array( [4, 12, -3] )
from numpy import linalg
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [71]:
# проверка верности (задание 3)

np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [98]:
# Задача 4
# Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
# Остальные столбцы - количество покупок категорий товаров этим пользователем:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
# На сайт заходит очередной посетитель next_user_stats, о покупках которого известно следующее
# Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
Length_next_user = np.linalg.norm(next_user_stats)
cosine = [] #список для записи данных косинусного сходства next_user_stats с каждым юзером х в users_stats
for x in users_stats:
    Length_user = np.linalg.norm(x) #для каждого юзера х в users_stats находим длину вектора покупок
    cosine.append(np.dot( x, next_user_stats ) / ( Length_user * Length_next_user ))#  находим косинусное сходство next_user_stats с х и записываем в cosine
print(cosine)
result = np.array(cosine) # перевожу список в массив
result.argmax() # получаю номер пользователя, имеющего максимальное скалярное произведение с Length_next_user - получается 7 - т.е. это восьмая строка матрицы

[0.19999999999999996, 0.8451542547285165, 0.3999999999999999, 0.7905694150420948, 0.3999999999999999, 0.0, 0.0, 0.9486832980505138, 0.0, 0.0]


7